services:
  # 🦓 ZooKeeper (Kafka dependency)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - herd-net

  # 🐘 Kafka Broker
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"   # internal use
      - "29092:29092" # host access
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Two listeners: internal (for containers) + external (for host)
      KAFKA_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 3
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 40s
    networks:
      - herd-net

  # 📊 Kafdrop UI (Kafka topic browser)
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_PORT: 9000
    ports:
      - "9000:9000"
    networks:
      - herd-net

  # 📦 Collector (Event producer)
  collector:
    build: ../collector
    container_name: collector
    depends_on:
      - kafka
    ports:
      - "3000:3000"
    environment:
      KAFKA_BROKERS: "kafka:9092"
      TOPIC: "user_events"
      PORT: 3000
      KAFKAJS_NO_PARTITIONER_WARNING: 1
    networks:
      - herd-net

  # ⚙️ Backend (FastAPI)
  backend:
    build: ../backend
    container_name: backend
    depends_on:
      - kafka
    ports:
      - "8000:8000"
    environment:
      KAFKA_BROKERS: "kafka:9092"
    networks:
      - herd-net

# 🌐 Shared network for all services
networks:
  herd-net:
    driver: bridge